### ISSUE TITLE
something about  discriminator

### ISSUE THREAD

**Issue by liang233** [xinntao/ESRGAN#40]
hello，the discriminator ,in pix2pix uses patchgan but srgan do not use the structure and pix2pix use the
connection of  fake image and real image while srgan only use fake image as input，how to choose two differnet structure ？ thanks

**Comment by xinntao** [comment]
Usually determined by the experiments. And the original discriminator seems to work fine. 

PatchGAN seems to be suitable for SR because SR focuses more on local textures. But too shallow layers may lead to unsatisfactory results. I have not tried much about this. 
From my previous exp, concatenating the faking and real images does not improve the results.

**Comment by liang233** [comment]
thanks
